# Generated by Django 4.1.4 on 2023-06-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacymission', models.CharField(max_length=200)),
                ('pharmacyvission', models.CharField(max_length=200)),
                ('pharmacybackground', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('whatsappnumber', models.CharField(max_length=200)),
                ('othernumber', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosmeticname', models.CharField(max_length=100)),
                ('cosmeticprice', models.CharField(max_length=200)),
                ('cosmeticcategory', models.CharField(max_length=200)),
                ('cosmeticamount', models.CharField(max_length=200)),
                ('cosmeticinputdate', models.CharField(max_length=200)),
                ('cosmeticconfigurationdate', models.CharField(max_length=200)),
                ('cosmeticexpiredate', models.CharField(max_length=200)),
                ('cosmeticlogo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=100)),
                ('medicineprice', models.CharField(max_length=200)),
                ('medicinecategory', models.CharField(max_length=200)),
                ('medicineamount', models.CharField(max_length=200)),
                ('medicineinputdate', models.CharField(max_length=200)),
                ('medicineconfigurationdate', models.CharField(max_length=200)),
                ('medicineexpiredate', models.CharField(max_length=200)),
                ('medicinelogo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendername', models.CharField(max_length=100)),
                ('senderaddress', models.CharField(max_length=200)),
                ('dateposted', models.CharField(max_length=200)),
                ('timeposted', models.CharField(max_length=200)),
                ('statusorder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyname', models.CharField(max_length=200)),
                ('ownername', models.CharField(max_length=200)),
                ('pharmacyaddress', models.CharField(max_length=200)),
                ('businesslicence', models.CharField(max_length=200)),
                ('pharmacycontact', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
    ]
